#if !canImport(ObjectiveC)
import XCTest

extension EasyDLTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EasyDLTests = [
        ("testCache", testCache),
        ("testCancel", testCancel),
        ("testExample", testExample),
        ("testFailure", testFailure),
        ("testProgress", testProgress),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(EasyDLTests.__allTests__EasyDLTests),
    ]
}
#endif
